name: dyanburgess
favicon: null
layout_spectrum: 0.10232114139944315
typography_spectrum: 0.6404527879785746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9747725613415241
  lightness: 0.347735971910879
  saturation: 0.9294552167411894
  rhythmicContrast: 0.7866654675453901
purpose: []
