name: dyanburgess
favicon: null
layout_spectrum: 0
typography_spectrum: 0.57327
title: The Story Curator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#81111a'
    - '#58595b'
    - '#b2b2b3'
    - '#8b8c8e'
  brandStrength: 0.9747725613415241
  lightness: 0.347735971910879
  saturation: 0.9294552167411894
  rhythmicContrast: 0.7866654675453901
purpose: []
